dvandal/cryptonote-nodejs-pool

- lib/paymentProcessor.js
If you try to mine with (wallet.payment_id.number) payment process fail with other payments in same transaction
> Clean payment_id

- website_example/lang/es.json
Some changes in spanish translation file
> Updated es.json

- config_examples/croat.json
More info at https://croat.cat/
> CroatCoin config file

- config_examples/bytecoin.json
Add this confg.json danval for bytecoin
> Create bytecoin config.json

- config_examples/myztic.json
@dvandal lemme know if you need any changes. Thanks!
> Added config for Myztic (MZT)

- website_example/pages/getting_started.html
Added cn variant and algo descriptor.
> Update for Masari fork

- lib/api.js
> fix content-length bug on dealing with other utf8 characters

- lib/api.js
`let` -> `var` (let isn't supported until nodejs 8)
> Fix nodejs 4 compatibility

- lib/pool.js
please review this, there are surely loads or errors
> added xmr-node-proxy support

- config_examples/monero.json
- config_examples/parsicoin.json
- website_example/pages/getting_started.html
> ParsiCoin Config + Monero v8 Support

- config_examples/ultranote.json
> Added UltraNote (XUN)

- config_examples/loki.json
- config_examples/monero.json
Loki tested to be working
Monero untested but should work
> update coin config examples

- Dockerfile
- lib/apiInterfaces.js
I added the ability to use passwords to access the wallet/services RPC, for use with Turtlecoin / Athena
> Add rpc password

- config_examples/dragonglass.json
{Dragonglass} DRGL
CryptoNote CNv8
> Add dragonglass.json

- config_examples/qwertycoin.json
Qwertycoin forked back to Cryptonight_Classic
> Qwertycoin forked to Cryptonight_Classic

- config_examples/bitcoinmono.json
I forgot to change the numbers last time.
> Update payments config

- config_examples/parsicoin.json
ParsiCoin Will SWAP on Version 3
> New ParsiCoin Config for V3+

- config_examples/italocoin.json
> update italo Algo to cn/r

- config_examples/loki.json
- config_examples/wownero.json
- lib/pool.js
- website_example/pages/getting_started.html
Uses xmrig variants 17/18 for RandomWOW/RandomXL (and in the future variant 0 should work fine for Monero).
Note that this will not work until https://github.com/MoneroOcean/node-cryptonight-hashing/pull/32 is merged!
> Add support for randomx mining

- lib/api.js
- lib/blockUnlocker.js
- lib/configReader.js
- website_example/pages/home.html
- website_example/pages/worker_stats.html
I've made a patch that will enable devDonation setting in json, the minimum donation is 0.2%.
Setting a lower then minimum donation will result in setting the donation to 0.2% (reported via log/frontend).
Address issue #517
> Developer Donations

- website_example/pages/getting_started.html
> WIP: Update Algo information on front-end

- website_example/pages/getting_started.html
This aligns front-end algorithms with the MoneroOcean hashing module.
Configurations will need to be updated accordingly.
> Update front-end algorithm information

- website_example/pages/home.html
Reverts dvandal/cryptonote-nodejs-pool#523
> Revert "Use CSS background color with all infoBoxes"

- website_example/js/common.js
- website_example/pages/home.html
- website_example/pages/worker_stats.html
Fixes up some ugliness
@muscleman I am not to sure how to adjust alignment on worker statistics graphs so you may want to have a look at that after.
Live pool with PR merged: https://funwithcrypto.tk/tkts/
> More Fixes

- config_examples/talleo.json
- lib/childDaemon.js
- lib/daemon.js
- lib/pool.js
- package.json
- website_example/pages/getting_started.html
> Talleo Support

- website_example/pages/faq.html
`lastReport`, `lastNotify`, and `lastBlocks` are not defined variables.
> Fix Telegram bot on FAQ Page

- config_examples/fandomgold.json
Dragonglass rebrands to [Fandom Gold](https://fandom.gold)
current mining algorithm: cnv8
> add Fandom Gold config example

- Dockerfile
- lib/pool.js
- lib/utils.js
- package.json
fix dockerfile to work + the haven offshore support
> Fix Dockerfile + Haven

- config_examples/xolentum.json
Adds config example for Xolentum - https://www.xolentum.org
Courtesy : Eskal from Let's Hash It
> Add config example for Xolentum

- package.json
removed haven breaking changes
> [removed haven breaking changes] Update package.json

- lib/pool.js
removed haven breaking changes
> [removed haven breaking changes] Update pool.js

- lib/utils.js
removed haven breaking changes
> [removed haven breaking changes] Update utils.js

- README.md
update readme:
-add options from recent commits to examples
-add pools
> add pubAddressPrefix to config example

- lib/utils.js
This needs to be merged to fix Node versions > 10 #646
> remove unnecessary call to addressBase58

- lib/utils.js
new Buffer is now Buffer.from 
Reference: https://stackoverflow.com/questions/52165333/deprecationwarning-buffer-is-deprecated-due-to-security-and-usability-issues/52165509
> update for node v > 10

- config_examples/societatis.json
Adds config example for Societatis [SCTS] https://societatis.io/
“an organization formed for a particular purpose“
> Add config example for SOCIETATIS

- website_example/pages/getting_started.html
If someone can look over this and make sure mining algos are all properly accounted for that would be great. I did the best I could from the xmrig repository. But I don't mine all these coins, so best to be sure. Thanks.
> add support for xmrigAlgo handling
