README.md

Fixed cryptonight_light typo.
From `cryptonight_lite` to `cryptonight_light`.

Fix cryptonight_light typo

---

lib/api.js
website_example/pages/home.html
website_example/pages/market.html
website_example/pages/pool_blocks.html
website_example/pages/worker_stats.html

The difficulty and height on the main page currently show the
difficulty and height of the previous block, but the pool is actually
currently working on a different diff/height.
This commit fetches the current network diff/height from the daemon and
updates the display to show them rather than the previous block values.

Show current network diff/height rather than last block diff/height

---

lib/paymentProcessor.js

If a payment notification fails we can end up in a situation where a
payment has gone ahead but isn't yet recorded in the pool, leading to a
double payment.
This commit defers invoking the notification code until after payments
are complete to avoid the potential issue.

Defer payment notification until payments complete

---

lib/pool.js

Pool ops can easily see what hard fork version and cn_variant they are mining on for a particular coin in the log.
This is tested on a few of my pools and I thought you might like the contribution. More to come if this get's merged. Thank you for your contributions. 
Screenshot:

Add hard fork version and cn_variant to the log

---

lib/telegramBot.js

Typo in the input variable broke the notify ADDR command.
Fixes #203 
Fixes #176

Fix `/notify ADDR` and `/report ADDR` telegram commands

---

website_example/pages/home.html
website_example/pages/market.html
website_example/pages/worker_stats.html

The intervals for drawing charts don't get destroyed, which can cause
some chart wonkiness such as the worker stats page getting replaced
with the overall pool hashrate (since the canvas id's are the same).
It can also cause some chart flickering when switching back and forth
between pages, since the repeated page ends up with multiple intervals
trying to draw the same chart.
This commit removes the interval when the page is destroyed so that
there should only be one chart drawing interval active at a time.

Clear chart intervals when destroying a page

---

README.md
lib/api.js
lib/blockUnlocker.js
lib/pool.js
website_example/js/common.js
website_example/pages/admin/statistics.html
website_example/pages/payments.html
website_example/pages/worker_stats.html
website_example/themes/default.css

A NiceHash pool hopper decided to grace my pool with his presence recently, so I looked into the pool's slush mining support.  I found a couple bugs and some limitations that I fixed/improved:
- when slush mining was enabled actual shares were only estimated; this commit splits up the scores and shares values so that accurate shares can still be reported.
- when an orphan was found during unlocking, the shares (i.e. score) of miners was re-added to the current score.  This is just plain wrong under slush mining (it's kind of weird under prop mining too) since it's transplating shares 2 hours into the future.  This isn't great under prop, but can be a disaster under slush (particularly when the orphaned block took exceptionally long since the orphaned scores will dominate the current block …

Slush reward updates

---

lib/blockUnlocker.js

Only scores were being cleared when a block is unlocked or orphaned, but the actual shares submitted needs to be cleaned up as well.

Clear old `shares_actual` entries.

---

lib/pool.js

nodejs 4 doesn't appear to allow `let`, sadly.

Fix for nodejs 4

---

website_example/pages/home.html
website_example/pages/market.html
website_example/pages/pool_blocks.html
website_example/pages/worker_stats.html
website_example/themes/default.css

While recently restyling my pool, I found that changing the colour of the charts requires editing the javascript, which doesn't seem particularly nice (and makes upgrades more difficult).  I came up with a solution to control the colours via the css, so that you can override it with an addition to `custom.css`.
This adds a hidden `<a>` tag after each chart `<canvas>` with a css-defined background-color, border-color, and width.  These are then used by the chart javascript to set the chart's background-color, border-color, and border-width.
The main advantage here is that it allows a site to change the chart colors via custom.css rather than needing to edit the javascript that generates the charts.
It's also possible to color just one chart differently by adding css such as:
```CSS
.chart …
```

Use css rules for chart colors

---

website_example/pages/payments.html

Currently **payment.time** is used as a unique ID for payment table rows. This could be an issue if multiple payments has exactly same timestamps (highly unlikely but possible) as only 1 payment, out of all the payments with same timestamps will be shown. 
Using **payment.hash** as table row ID will ensure that all the rows has a unique ID and would prevent issues that come with multiple payments with same timestamps.

Use payment.hash as a unique ID for payment rows

---

lib/telegramBot.js

If attempting to request a report for a miner that doesn't exist on the
pool the telegram bot crashes (`data.stats` is undefined, leading to an
exception when calling `data.stats.hashrate`).
This adds a new "not found" error message if the lookup doesn't return
any stats.
Additionally this fixes an error in the event of a harder lookup failure
(e.g. from an error connecting to the api) not using the correct
variable for the recipient.

Fix telegram crash when requesting report for invalid addr

---

README.md
config_examples/loki.json
lib/api.js
lib/blockUnlocker.js

Loki, in particular, no longer uses a constant fee: most blocks don't include the governance reward, but then there is an occassional very large reward with includes a large governance reward.  The proper solution here is to use the first vout to extract the miner reward, which this patch adds support for.
I don't actually have a Loki pool to test this on; it is based on a patch for a heavily-modified pool.  I'd appreciate if someone could give it a try and confirm that it works on an actual loki pool before it gets merged.

Add ability to use first vout for block reward

---

config_examples/graft.json
website_example/pages/getting_started.html

Added correct handling of CryptoNight v8 ReverseWaltz. 
[MoneroOcean/node-cryptonight-hashing](https://github.com/MoneroOcean/node-cryptonight-hashing) already has CryptoNight v8 ReverseWaltz support.
Please, let me know, if you need something else for correct support of CryptoNight v8 ReverseWaltz.

Correct handling of CryptoNight v8 ReverseWaltz

---

lib/blockUnlocker.js
lib/configReader.js

This makes the dev donation optional, but defaults to 0.2% if not set in config.
Referencing @dvandal https://github.com/dvandal/cryptonote-nodejs-pool/issues/517#issuecomment-554607215

Restore optional dev donation

---

init.js

- Several places in api.js assume childPools is defined, set if to an
empty array by default so front-end still works

Prevent API crashes if childPools not defined in config.json

---

lib/paymentProcessor.js

- 'mixin' parameter was removed from RPC API, see:
https://github.com/monero-project/monero/commit/023f2c77472e56751b46820a3bbb20dde82b0185#diff-27aa76d79152f1d9630da4e9f06b9067
- For backwards compatibility new RPC parameter is only used if user
includes 'ringSize' parameter in payments section of config.json

Support 'ring_size' transfer RPC parameter for payments

---

config_examples/talleo.json

xmrig recently added support for Talleo's algorithm in development branch. This fix makes sure xmrig uses correct algorithm even if user specifies wrong algorithm. Older xmrig versions will print error message to make it clear user is trying unsupported combination.

Talleo algorithm negotiation for xmrig

---

lib/pool.js
lib/utils.js
package.json

Haven Apollo now provides offshore functionality, which requires a change to the block_header format (among other changes). In order for the pool code to support this, a new module has been created to sit alongside **MoneroOcean's cryptoforknote-util**. 
This pull request adds the new **haven-nodejs-wrapper** module as a dependency to the pool code.

added haven-offshore support to pool code

---

lib/api.js

trtl v.0.22.0: The /getinfo, /getheight, /getpeers, and /getfee calls have been removed in lieu of /info, /height, /peers, and /fee.
This quick fix fallback to getlastblockheader if get_info fail because of empty reply.

fix trtl daemon get_info

---

lib/daemon.js

This allows miners to continue mining previous block height until the new block has at least 1 transaction. Otherwise the new block template would get rejected if a miner manages to solve it before it is refreshed with more transactions.
It is currently not possible to merge-mine Talleo so this enhancement is only required for parent daemon.

[Talleo] Discard block templates with 0 transactions starting from height 10000.

---

config_examples/safex/config.json

fixed the config example for safex. the cnVariant and blobtype were mixed up, and the fix for rpc height is needed

fix safex config example

---

package.json

When using `async@3.2.0` it gives you the following error:
```JS
TypeError: blocks.map is not a function                                                                                                                                     
at /root/cryptonote-nodejs-pool/lib/blockUnlocker.js:120:31                                                                                                               
at nextTask (/root/cryptonote-nodejs-pool/node_modules/async/dist/async.js:5791:27) 
at next (/root/cryptonote-nodejs-pool/node_modules/async/dist/async.js:5799:13)                                                                                           
at /root/cryptonote-nodejs-pool/node_modules/async/dist/async.js:329:20             
at …
```

Fix the blockUnlocker.js from crashing
